import {
  boolean,
  index,
  json,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const agentRuns = pgTable(
  "agent_runs",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").notNull(),
    userId: text("user_id"),
    parentMessageId: text("parent_message_id"),
    retryOfRunId: text("retry_of_run_id"),
    userPrompt: text("user_prompt").notNull(),
    reasoningEffort: text("reasoning_effort"),
    model: text("model"),
    planMode: boolean("plan_mode").notNull().default(false),
    kind: text("kind"),
    intent: json("intent"),
    plan: json("plan"),
    status: text("status").notNull(),
    failureCode: text("failure_code"),
    modelUsage: json("model_usage"),
    thinking: json("thinking"),
    affectedFiles: json("affected_files").notNull(),
    validationResult: json("validation_result"),
    codeToolRunState: json("code_tool_run_state"),
    error: json("error"),
    progressTimeline: json("progress_timeline").notNull().default([]),
    planPhase: json("plan_phase"),
    clarificationSnapshot: json("clarification_snapshot"),
    startedAt: timestamp("started_at").notNull(),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").notNull(),
    updatedAt: timestamp("updated_at").notNull(),
  },
  (table) => ({
    projectIdx: index("agent_runs_project_idx").on(table.projectId),
    userIdx: index("agent_runs_user_idx").on(table.userId),
    retryIdx: index("agent_runs_retry_idx").on(table.retryOfRunId),
    statusIdx: index("agent_runs_status_idx").on(table.status),
    kindIdx: index("agent_runs_kind_idx").on(table.kind),
  }),
);
