import {
  index,
  json,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const projectStates = pgTable(
  "project_states",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").notNull(),
    userId: text("user_id"),
    status: text("status").notNull(),
    stack: json("stack").notNull(),
    packagePolicy: json("package_policy").notNull(),
    ecommerceSpec: json("ecommerce_spec").notNull(),
    brand: json("brand").notNull(),
    pages: json("pages").notNull(),
    features: json("features").notNull(),
    constraints: json("constraints").notNull(),
    fileManifest: json("file_manifest").notNull(),
    decisionLog: json("decision_log").notNull(),
    recentChanges: json("recent_changes").notNull(),
    devRuntime: json("dev_runtime").notNull().default({
      status: "stopped",
      enabled: false,
      pid: null,
      port: null,
      previewHost: null,
      cloudflareDnsRecordId: null,
      dnsStatus: "none",
      installStatus: "idle",
      installStartedAt: null,
      installCompletedAt: null,
      devStartedAt: null,
      previewUrl: null,
      lastAccessedAt: null,
      installLog: null,
      devLog: null,
      lastError: null,
      lastErrorTier: null,
      retryCount: 0,
      maxRetries: 3,
      operatorAttentionRequired: false,
      fixAttempts: [],
    }),
    createdAt: timestamp("created_at").notNull(),
    updatedAt: timestamp("updated_at").notNull(),
  },
  (table) => ({
    projectIdx: uniqueIndex("project_states_project_idx").on(table.projectId),
    userIdx: index("project_states_user_idx").on(table.userId),
  }),
);
