import fs from "node:fs/promises";
import path from "node:path";
import type { CodexEnvAvailable } from "@/server/env/codex";

const PROFILE_NAME = "cloud_ai";

function buildProfileToml(env: CodexEnvAvailable): string {
  const lines: string[] = [];
  lines.push(`# Generated by cloud-ai-builder. Do not edit by hand.`);
  lines.push(``);
  lines.push(`[profiles.${PROFILE_NAME}]`);
  lines.push(`model = "${env.model}"`);
  lines.push(`provider = "${PROFILE_NAME}"`);
  lines.push(``);
  lines.push(`[providers.${PROFILE_NAME}]`);
  if (env.baseUrl) lines.push(`base_url = "${env.baseUrl}"`);
  lines.push(`env_key = "CODEX_API_KEY"`);
  lines.push(``);
  return lines.join("\n");
}

export async function writeCodexConfig(env: CodexEnvAvailable): Promise<string> {
  await fs.mkdir(env.codexHome, { recursive: true, mode: 0o700 });
  const target = path.join(env.codexHome, "config.toml");
  await fs.writeFile(target, buildProfileToml(env), { mode: 0o600 });
  return target;
}

export async function deleteCodexConfig(env: CodexEnvAvailable): Promise<void> {
  const target = path.join(env.codexHome, "config.toml");
  await fs.rm(target, { force: true });
}

export const CODEX_PROFILE_NAME = PROFILE_NAME;
