export const ThinkingResultJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "intent",
    "confidence",
    "language",
    "userWish",
    "ecommerceContext",
    "projectAction",
    "constraints",
    "risk",
    "normalizedTask",
    "downstream",
  ],
  properties: {
    intent: { type: "string", enum: ["init_project", "add_feature", "modify_design", "modify_content", "modify_products", "fix_bug", "integrate_service", "explain_project", "unknown"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    language: { type: "string", enum: ["vi", "en", "mixed", "unknown"] },
    userWish: {
      type: "object",
      additionalProperties: false,
      required: ["rawPrompt", "explicitRequests", "implicitRequests", "inferredEcommerceGoals", "outOfScopeRequests"],
      properties: {
        rawPrompt: { type: "string" },
        explicitRequests: { type: "array", items: { type: "string" } },
        implicitRequests: { type: "array", items: { type: "string" } },
        inferredEcommerceGoals: { type: "array", items: { type: "string" } },
        outOfScopeRequests: { type: "array", items: { type: "string" } },
      },
    },
    ecommerceContext: {
      type: "object",
      additionalProperties: false,
      required: ["storeType", "affectedPages", "affectedSections", "affectedFeatures", "affectedEntities", "conversionGoal"],
      properties: {
        storeType: { type: "string", enum: ["fashion", "cosmetics", "electronics", "furniture", "food", "digital", "general", "unknown"] },
        affectedPages: { type: "array", items: { type: "string" } },
        affectedSections: { type: "array", items: { type: "string" } },
        affectedFeatures: { type: "array", items: { type: "string" } },
        affectedEntities: { type: "array", items: { type: "string" } },
        conversionGoal: { type: "string", enum: ["increase_add_to_cart", "increase_checkout_completion", "improve_product_discovery", "increase_trust", "improve_brand_perception", "improve_mobile_ux", "none", "unknown"] },
      },
    },
    projectAction: {
      type: "object",
      additionalProperties: false,
      required: ["shouldInitProject", "shouldModifyExistingProject", "shouldAskClarification", "clarificationQuestion", "requiresSourceInit", "requiresPatchGeneration", "requiresValidation", "requiresPreviewRefresh"],
      properties: {
        shouldInitProject: { type: "boolean" },
        shouldModifyExistingProject: { type: "boolean" },
        shouldAskClarification: { type: "boolean" },
        clarificationQuestion: { anyOf: [{ type: "string" }, { type: "null" }] },
        requiresSourceInit: { type: "boolean" },
        requiresPatchGeneration: { type: "boolean" },
        requiresValidation: { type: "boolean" },
        requiresPreviewRefresh: { type: "boolean" },
      },
    },
    constraints: {
      type: "object",
      additionalProperties: false,
      required: ["preserveExistingDesign", "preserveExistingFeatures", "requestedStackChange", "requestedDestructiveChange", "forbiddenActions"],
      properties: {
        preserveExistingDesign: { type: "boolean" },
        preserveExistingFeatures: { type: "boolean" },
        requestedStackChange: { type: "boolean" },
        requestedDestructiveChange: { type: "boolean" },
        forbiddenActions: { type: "array", items: { type: "string" } },
      },
    },
    risk: {
      type: "object",
      additionalProperties: false,
      required: ["level", "reasons"],
      properties: {
        level: { type: "string", enum: ["low", "medium", "high"] },
        reasons: { type: "array", items: { type: "string" } },
      },
    },
    normalizedTask: {
      type: "object",
      additionalProperties: false,
      required: ["title", "description", "acceptanceCriteria", "implementationHints"],
      properties: {
        title: { type: "string" },
        description: { type: "string" },
        acceptanceCriteria: { type: "array", items: { type: "string" } },
        implementationHints: { type: "array", items: { type: "string" } },
      },
    },
    downstream: {
      type: "object",
      additionalProperties: false,
      required: ["recommendedNextStep", "priority"],
      properties: {
        recommendedNextStep: { type: "string", enum: ["ask_clarification", "init_source", "create_plan", "generate_patch", "explain_only", "reject_or_safe_redirect"] },
        priority: { type: "string", enum: ["low", "normal", "high"] },
      },
    },
  },
} as const;
