export const DESIGN_ERROR_CODES = {
  DESIGN_FILE_MISSING: "DESIGN_FILE_MISSING",
  DESIGN_RULES_REQUIRED: "DESIGN_RULES_REQUIRED",
  DESIGN_TEMPLATE_LEAK: "DESIGN_TEMPLATE_LEAK",
  DESIGN_TOKEN_LITERAL_OFF_RULE: "DESIGN_TOKEN_LITERAL_OFF_RULE",
  DESIGN_PATCH_AMBIGUOUS_TOKEN_REQUEST: "DESIGN_PATCH_AMBIGUOUS_TOKEN_REQUEST",
  DESIGN_PATCH_TOKEN_ROLE_NOT_FOUND: "DESIGN_PATCH_TOKEN_ROLE_NOT_FOUND",
  DESIGN_PATCH_STRUCTURE_BROKEN: "DESIGN_PATCH_STRUCTURE_BROKEN",
} as const;

export type DesignErrorCode =
  (typeof DESIGN_ERROR_CODES)[keyof typeof DESIGN_ERROR_CODES];
