export const DESIGN_ERROR_CODES = {
  DESIGN_FILE_MISSING: "DESIGN_FILE_MISSING",
  DESIGN_RULES_REQUIRED: "DESIGN_RULES_REQUIRED",
  DESIGN_TEMPLATE_LEAK: "DESIGN_TEMPLATE_LEAK",
  DESIGN_TOKEN_LITERAL_OFF_RULE: "DESIGN_TOKEN_LITERAL_OFF_RULE",
  DESIGN_PATCH_AMBIGUOUS_TOKEN_REQUEST: "DESIGN_PATCH_AMBIGUOUS_TOKEN_REQUEST",
  DESIGN_PATCH_TOKEN_ROLE_NOT_FOUND: "DESIGN_PATCH_TOKEN_ROLE_NOT_FOUND",
  DESIGN_PATCH_STRUCTURE_BROKEN: "DESIGN_PATCH_STRUCTURE_BROKEN",
  DESIGN_TAXONOMY_FAIL: "DESIGN_TAXONOMY_FAIL",
  DESIGN_VIBE_FAIL: "DESIGN_VIBE_FAIL",
  DESIGN_COMPOSITION_FAIL: "DESIGN_COMPOSITION_FAIL",
  DESIGN_AFFINITY_FAIL: "DESIGN_AFFINITY_FAIL",
  DESIGN_CROSS_FILE_FAIL: "DESIGN_CROSS_FILE_FAIL",
  DESIGN_LEAK_FAIL: "DESIGN_LEAK_FAIL",
  DESIGN_MANIFEST_CORRUPT: "DESIGN_MANIFEST_CORRUPT",
  DESIGN_TAXONOMY_SOFT_MISS: "DESIGN_TAXONOMY_SOFT_MISS",
  DESIGN_ANCHOR_MISMATCH: "DESIGN_ANCHOR_MISMATCH",
} as const;

export type DesignErrorCode =
  (typeof DESIGN_ERROR_CODES)[keyof typeof DESIGN_ERROR_CODES];

export type ManualReviewReason =
  | "taxonomy"
  | "vibe"
  | "composition"
  | "affinity"
  | "cross-file"
  | "leak"
  | "manifest-corrupt";
