import type { WebsiteSpec } from "../project/project-state.schema";
import type { ProjectDesignRuleContext } from "../code-tools/services/design-file-service.server";

export function buildRetailInitPrompt(input: {
  userPrompt: string;
  websiteSpec: WebsiteSpec;
  designRules: ProjectDesignRuleContext;
}): string {
  const { websiteSpec: spec } = input;
  const productList = spec.products
    .map(
      (p) =>
        "- " +
        p.name +
        (p.price ? " ($" + p.price + ")" : "") +
        (p.category ? " [" + p.category + "]" : ""),
    )
    .join("\n");

  return [
    "CREATE all files listed below using project_create_file tool.",
    "Do NOT read files first. Do NOT inspect. Just CREATE the files.",
    "",
    "STORE: " + spec.store.name + " (" + spec.store.type + ")",
    "PRODUCTS:",
    productList,
    "",
    "DESIGN: This project has its own DESIGN.md (visual identity generated for THIS store). Call project_read_design_rules BEFORE creating UI files. Use the palette, typography, spacing, and component rules from sections 1-8. Do NOT use the example colors from any other project.",
    "",
    "IMPORTS AVAILABLE:",
    '- { websiteConfig } from "@/lib/website-config"',
    '- { formatMoney, resolveProductPrice } from "@/lib/format-money"',
    '- { cn } from "@/lib/utils"',
    '- { StoreProvider, useStore } from "@/app/store-provider"  // useStore() returns { storeDetail, isLoading, error, refetch, isUsingSampleData }; storeDetail.setting?.currency carries the ISO currency (default fallback: AUD)',
    '- { CartProvider, useCart } from "@/app/cart-provider"  // empty scaffold for now — do NOT add cart state here',
    '- { sampleStore } from "@/data/sample-store"',
    '- { useStoreDetail, hasStoreSlug, type StoreDetail, type StoreSetting } from "@/services/store/use-store-detail"',
    '- { useProductsList, type Product, type ProductModel, type ProductsList } from "@/services/store/use-products-list"',
    '- { useProductDetail, type ProductDetail } from "@/services/store/use-product-detail"',
    '- { useCategoriesList, type Category, type CategoriesList } from "@/services/store/use-categories-list"',
    '- { useProductSuggestions, type ProductSuggestionsList } from "@/services/store/use-product-suggestions"',
    "",
    "// @/data/products and @/data/categories exist as internal sample fallbacks for the hooks above. Routes and store components MUST NOT import them directly — always consume the hooks.",
    "",
    "PRICE & CURRENCY RULES:",
    "- Product price values (product.price, product.compareAtPrice, product.defaultModel.price, product.models[].price) are integer cents in state, hooks, and sample data. Never pre-divide.",
    "- Render price ONLY via formatMoney(resolveProductPrice(product), { currency }) where currency = useStore().storeDetail?.setting?.currency ?? 'AUD'. resolveProductPrice falls back through defaultModel.price → models[0].price → price using lodash _.get.",
    "- formatMoney divides cents by 100 internally using lodash _.divide and rounds with _.round before formatting via Intl.NumberFormat. Components MUST NOT call formatMoney(product.price) directly.",
    "- Use lodash helpers (_.get, _.divide, _.round) inside any new price/arithmetic helpers; the generated app has lodash and @types/lodash installed.",
    "",
    "PRODUCT IMAGE RULES:",
    "- Render product visual via product.image ?? product.images?.[0] using <img src=... className='... object-cover' />. Fall back to the existing bg-gradient placeholder ONLY when neither field is present.",
    "",
    "BRAND NAME RULES:",
    "- ALWAYS source the brand/store name from websiteConfig.store.name (or useStore().storeDetail?.name when inside StoreProvider). NEVER hardcode strings like 'AI Storefront', 'AI Store front', 'Demo Store', or any placeholder brand name in JSX, headings, eyebrows, footers, page titles, or meta tags.",
    "",
    "ROUTING (TanStack Start):",
    '- createFileRoute("/path")({ component: Fn }) for pages',
    '- createRootRoute({ component: Fn }) for __root.tsx',
    '- Trailing slash for index: createFileRoute("/products/")',
    '- Dynamic: createFileRoute("/products/$productId")',
    '- Route.useParams() for params',
    '- NEVER edit routeTree.gen.ts',
    "",
    "CREATE THESE FILES:",
    "",
    "src/components/ui/button.tsx - shadcn Button with cva, variants: default/destructive/outline/secondary/ghost/link, sizes: default/sm/lg/icon, rounded-full, active:scale-95, use cn()",
    "",
    "src/components/ui/card.tsx - shadcn Card/CardHeader/CardContent/CardFooter/CardTitle/CardDescription, rounded-lg border shadow-sm",
    "",
    "src/app/store-provider.tsx - StoreProvider focuses ONLY on store detail. When VITE_STORE_SLUG is set, fetch store detail via useStoreDetail and expose { storeDetail, isLoading, error, refetch, isUsingSampleData=false }. When VITE_STORE_SLUG is missing, return sampleStore from @/data/sample-store with isUsingSampleData=true. Do NOT include cart, order, or checkout state.",
    "",
    "src/app/cart-provider.tsx - CartProvider scaffold that wraps children with a CartContext. For now, expose an empty context value and useCart hook. Do NOT add cart state, atoms, or handlers yet.",
    "",
    "src/data/sample-store.ts - sampleStore constant matching StoreDetail shape ({ id, slug, name, description }) used as fallback when VITE_STORE_SLUG is missing.",
    "",
    "src/components/ui/input.tsx - shadcn Input, h-10 rounded-md border px-3 py-2, focus-visible:ring-2",
    "",
    "src/components/ui/badge.tsx - shadcn Badge with cva, variants: default/secondary/destructive/outline/sale(amber-600), rounded-full",
    "",
    "src/components/ui/separator.tsx - shadcn Separator using @radix-ui/react-separator",
    "",
    "src/components/ui/label.tsx - shadcn Label using @radix-ui/react-label",
    "",
    "src/components/ui/select.tsx - shadcn Select using @radix-ui/react-select with SelectTrigger/SelectContent/SelectItem/SelectValue",
    "",
    "src/components/ui/radio-group.tsx - shadcn RadioGroup using @radix-ui/react-radio-group with RadioGroupItem",
    "",
    "src/components/ui/dialog.tsx - shadcn Dialog modal using @radix-ui/react-dialog with DialogTrigger/DialogContent/DialogHeader/DialogTitle/DialogDescription/DialogClose",
    "",
    "src/components/ui/sonner.tsx - Toaster wrapper using sonner; checkout uses toast.success after createOrder",
    "",
    "src/components/layout/site-header.tsx - Retail header with brand name (websiteConfig.store.name or useStore().storeDetail?.name) on the left, a search bar in the middle, and a ShoppingCart icon Button on the right. NO Home/Products/Orders nav links. NO mobile Sheet menu. sticky top-0 border-b. Search-bar accent colors MUST bind to the DESIGN.md primary token (lighter tint of primary for input fill, soft primary tint for the focus ring, primary for the submit button background, primary for match highlight) — do NOT hardcode rose/pink. Pill input: rounded-full, h-11, pl-5 pr-1.5 py-2.5, focus:outline-none focus:ring-2 with the primary-tinted ring, no border. Leading Lucide Search icon h-4 w-4 with a muted primary tint. Input class 'text-sm text-slate-700 placeholder:text-slate-400'; placeholder MUST be exactly 'What are you looking for?'. Trailing inset circular submit Button (type='submit', size='icon', h-9 w-9 rounded-full bg-primary hover:bg-primary/90 text-white) containing a white Lucide Search icon h-4 w-4. Submit (form onSubmit OR Enter) calls useNavigate() from @tanstack/react-router and navigate({ to: '/products', search: { q: value.trim() } }) when value is non-empty, then closes the dropdown. Debounce the suggestions input value by 800ms via a useEffect+setTimeout — track BOTH the raw input value (for the input field, dropdown visibility gating, and form submit) AND a debouncedValue (passed as the query to useProductSuggestions) so users can type freely without firing a request per keystroke. Suggestions dropdown renders below the input (absolute, w-full, mt-2) when the input is focused AND inputValue.trim().length > 0 AND suggestions.length > 0, with class 'rounded-2xl bg-white p-3 shadow-lg shadow-black/5' (no hard border). Inside: 'Suggestions' label (text-xs font-medium text-slate-400 mb-1) then suggestion rows ('flex items-center gap-3 px-2 py-2 rounded-lg cursor-pointer' with a primary-tinted hover background) each with a leading Lucide Search icon h-4 w-4 text-slate-400 and the suggestion text (text-sm text-slate-700). Clicking a row sets the input value to the suggestion, navigates to /products with search { q: suggestion }, and closes the dropdown. Highlight matched substrings of the current input value against each suggestion (case-insensitive) by escaping regex metacharacters in the query, splitting via new RegExp('(' + escaped + ')', 'gi'), and wrapping matched parts with <span className='text-primary'> — same weight, no background. Accessibility: input role='combobox' with aria-expanded and aria-controls='site-search-suggestions'; dropdown role='listbox' id='site-search-suggestions'; rows role='option' aria-selected. Keyboard: ArrowDown/ArrowUp move active row, Enter selects active row (or submits typed value when no row is active), Escape closes. Hide dropdown on outside click and on isError from the suggestions hook. Wire suggestions via useProductSuggestions({ storeId: useStoreDetail().data?.id, query: debouncedValue }) — do NOT branch on hasStoreSlug here, the hook handles the fallback internally.",
    "",
    "src/services/store/use-product-suggestions.ts - useProductSuggestions({ storeId, query }) hook. When VITE_STORE_SLUG exists AND storeId truthy AND query.trim().length > 0, call GET /api/v1/products/suggestions with params { storeId, query } via @tanstack/react-query useQuery; response shape ProductSuggestionsList = { total: number, data: string[] }. queryKey ['product-suggestions', storeId, query.trim()]; enabled = hasStoreSlug && Boolean(storeId) && query.trim().length > 0. When VITE_STORE_SLUG is missing OR query is empty, return a deterministic local sample list (filter product names from @/data/products by case-insensitive substring against query, dedupe, cap at 8) — mirror the sample-fallback pattern used by useProductsList. The hook returns { suggestions: string[], total: number, isLoading: boolean, isError: boolean, error: unknown, refetch: () => unknown }. Export ProductSuggestionsList type.",
    "",
    "src/components/layout/site-footer.tsx - Deep brand surface bg (use Deep Brand color from DESIGN.md section 2), white text, 4 cols (Shop/Support/Company/Connect), responsive grid",
    "",
    "src/components/store/hero-section.tsx - Headline from websiteConfig.content.heroTitle, subtitle, CTA Button to /products, gradient visual placeholder, split layout",
    "",
    "src/components/store/product-card.tsx - Card with product image, name, formatted price, sale Badge, Add to cart Button (toast placeholder; cart not wired yet), Heart wishlist. Render image via product.image ?? product.images?.[0] inside <img className='h-56 w-full object-cover' /> as a BARE element (NOT wrapped in a Link), falling back to the bg-gradient div only when both fields are missing. Wrap ONLY the product title text with <Link to='/products/$productId' params={{ productId: product.id }}> — the Link contains the <h3>{product.name}</h3>, never the image. Render price via formatMoney(resolveProductPrice(product), { currency: useStore().storeDetail?.setting?.currency ?? 'AUD' }).",
    "",
    "src/components/store/product-grid.tsx - Title, grid-cols-1 sm:2 lg:3 xl:4 gap-6, map products to ProductCard. Always consume useProductsList({ storeId: useStoreDetail().data?.id }) — the hook uses useInfiniteQuery and returns { products, total, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading, isError, refetch }. The hook itself returns sample fallback data with hasNextPage=false when VITE_STORE_SLUG is missing. Render the products array via .map and append a sentinel <div ref={loadMoreRef} /> after the grid; use an IntersectionObserver effect that calls fetchNextPage() when the sentinel intersects the viewport AND hasNextPage AND !isFetchingNextPage (rootMargin: '200px'). Show 'Loading more...' inside the sentinel while isFetchingNextPage. Render a loading skeleton during isLoading and an error UI with retry on isError. The product count text MUST come from the hook's total field. Do NOT import { products } from @/data/products and do NOT branch on hasStoreSlug.",
    "",
    "src/components/store/trust-signals.tsx - Truck/RotateCcw/Shield/Headphones icons, 4 items grid",
    "",
    "src/components/store/feature-band.tsx - Deep brand bg (use Deep Brand color from DESIGN.md section 2), headline, 2 Buttons (white filled + white outline)",
    "",
    "src/components/store/newsletter-section.tsx - Heading, Input + Button form, useState email",
    "",
    "src/components/store/cart-item.tsx - Thumbnail (product.image ?? product.images?.[0] via <img className='h-20 w-20 object-cover' />, fallback to bg-secondary div when missing), name, price formatted via formatMoney(resolveProductPrice(product), { currency }), static quantity display, disabled +/- and remove Buttons (cart wiring deferred). Currency from useStore().storeDetail?.setting?.currency ?? 'AUD'.",
    "",
    "src/components/store/order-card.tsx - Card with order#, date, status Badge, total, Link to detail",
    "",
    "src/routes/__root.tsx - createRootRoute, html/head(HeadContent)/body(Providers wrapping StoreProvider wrapping CartProvider wrapping SiteHeader/Outlet/SiteFooter/Toaster, then Scripts), import app.css",
    "",
    "src/routes/index.tsx - createFileRoute('/'), compose HeroSection/ProductGrid/TrustSignals/FeatureBand/NewsletterSection",
    "",
    "src/routes/products/index.tsx - createFileRoute('/products/'), title, category filter Buttons, sort Select, product grid, product count. Always consume useProductsList({ storeId: useStoreDetail().data?.id }) and useCategoriesList(storeId) — useProductsList uses useInfiniteQuery and returns { products, total, fetchNextPage, hasNextPage, isFetchingNextPage, isLoading, isError, refetch }; both hooks return sample fallback data when VITE_STORE_SLUG is missing. Implement the same infinite scroll pattern as product-grid: append a sentinel <div ref={loadMoreRef} /> after the grid and use an IntersectionObserver effect to call fetchNextPage() when intersecting AND hasNextPage AND !isFetchingNextPage (rootMargin: '200px'); show 'Loading more...' inside the sentinel while isFetchingNextPage. The product count text MUST come from the hook's total field. Render loading skeleton during isLoading and error UI with retry on isError. Do NOT import { products } or { categories } from @/data/* and do NOT branch on hasStoreSlug. The route MUST declare validateSearch on createFileRoute to coerce ?q to a trimmed string defaulting to '', read it via Route.useSearch(), and pass it as the query argument to useProductsList({ storeId, query }). The query string is part of the queryKey so useInfiniteQuery resets to page 1 naturally when q changes. Render a small 'Results for \"<q>\"' label above the grid when q is non-empty, and a 'No products match \"<q>\"' empty state when products.length === 0 AND !isLoading AND !isError.",
    "",
    "src/routes/products/$productId.tsx - createFileRoute('/products/$productId'), Route.useParams(), breadcrumb, split layout, hero image (product.image ?? product.images?.[0] via <img className='min-h-[520px] w-full object-cover' />, fallback to bg-gradient div when missing), name, formatted price via formatMoney(resolveProductPrice(product), { currency }), badge, description, quantity +/-, Add to cart Button. Currency from useStore().storeDetail?.setting?.currency ?? 'AUD'. Always consume useProductDetail(productId) — the hook itself returns sample fallback data when VITE_STORE_SLUG is missing. Render loading skeleton during isLoading and error UI with retry on isError. Do NOT import { products } from @/data/products and do NOT branch on hasStoreSlug.",
    "",
    "src/routes/cart.tsx - createFileRoute('/cart'), simple 'Cart coming soon' empty state with Continue Shopping link to /products. No cart state.",
    "",
    "src/routes/checkout.tsx - createFileRoute('/checkout'), shipping form (Input+Label) with react-hook-form+zod, Place Order Button shows toast.success placeholder; do NOT persist orders.",
    "",
    "src/routes/orders/index.tsx - createFileRoute('/orders/'), title, OrderCard list (empty for now), 'Shop now' Button. No order state.",
    "",
    "src/routes/orders/$orderId.tsx - createFileRoute('/orders/$orderId'), Route.useParams(), 'Order details unavailable' card, Back link.",
    "",
    "NOW CREATE ALL FILES using project_create_file. START IMMEDIATELY.",
  ].join("\n");
}
